on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true

      os:
        type: string
        default: ubuntu-latest

jobs:
  test:
    name: Run tests
    runs-on: ${{ inputs.os }}
    concurrency:
      group: build-${{ runner.os }}-${{ inputs.target }}-debug

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-rust
        with:
          target: ${{ inputs.target }}
          profile: debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: cargo test --target ${{ inputs.target }}
