on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true

      os:
        type: string
        default: ubuntu-latest

jobs:
  test:
    name: Run tests
    runs-on: ${{ inputs.os }}

    steps:
      - uses: moonrepo/setup-rust@v1
        with:
          targets: ${{ inputs.target }}
          inherit-toolchain: true
          cache-extra-identifier: ${{ inputs.os }}-${{ inputs.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: rui314/setup-mold@v1
        if: runner.os == 'Linux'

      - uses: actions/checkout@v6

      - name: Run tests
        run: cargo test --target ${{ inputs.target }}
